project:
  type: book
  output-dir: docs


book:
  title: "Time Series Analysis"
  author: "Yair Mau"
  favicon: archive/clock-history.png
  chapters:
    - index.qmd
    - part: introduction/introduction.qmd
      chapters:
      - introduction/first-steps.ipynb
    - part: smoothing/smoothing.qmd
      chapters:
        - smoothing/convolution.qmd
    - part: lags/lags.qmd
      chapters:
        - lags/cross-correlation.ipynb
        - lags/dynamic-time-warp.qmd
    - part: seasonality/seasonality.qmd
      chapters:
        - seasonality/seasonal-decomposition.ipynb
    - technical-stuff/technical-stuff.qmd
    - references.qmd
  sidebar:
    tools:
      - icon: house
        href: https://yairmau.com/
    logo: archive/clock-history.png
  search: true

bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    fontsize: 1.2em
    highlight-style: gruvbox
    include-in-header:
      - includes.html
  pdf:
    documentclass: scrreprt



