project:
  type: book
  output-dir: docs


book:
  title: "Time Series Analysis"
  author: "Yair Mau"
  favicon: archive/clock-history.png
  chapters:
    - index.qmd
    - part: "Basic data manipulation and plotting"
      chapters:
      - basics/pandas.qmd
      - basics/pyplot.qmd
      - introduction/first-steps.ipynb
    - part: "Outliers and Gaps"
      chapters:
      - outliers/zscore.qmd
    - part: "Resampling"
      chapters:
        - resampling/upsampling.qmd
        - resampling/downsampling.qmd
    - part: "Best practices"
      chapters:
        - best-practices/dates.qmd
    - part: "Smoothing"
      chapters:
        - smoothing/convolution.qmd
        - smoothing/LOESS.qmd
        - smoothing/perfect-smoother.qmd
    - part: "Stationarity"
      chapters:
        - stationarity/stochastic.qmd
        - stationarity/autocorrelation.qmd
    - part: "Time lags"
      chapters:
        - lags/cross-correlation.ipynb
        - lags/dynamic-time-warp.qmd
        - lags/LDTW.ipynb
    - part: "Frequency"
      chapters:
        - frequency/fourier.qmd
        - frequency/filtering.qmd
        - frequency/nyquist.qmd
    - part: "Seasonality"
      chapters:
        - seasonality/seasonal-decomposition.ipynb
        - seasonality/hilbert.qmd
    - part: "Rates of change"
      chapters:
        - rates-of-change/derivatives.qmd
        - rates-of-change/finite-differences.qmd
        - rates-of-change/fourier-based-derivatives.qmd
        - rates-of-change/LOESS-based-derivatives.qmd
    - part: "Forecasting"
      chapters:
        - forecasting/arima.qmd
    - technical-stuff/technical-stuff.qmd
    - references.qmd
  sidebar:
    collapse-level: 1
    tools:
      - icon: house-fill
        href: https://yairmau.com/
      - icon: bookmark-fill
        href: /references.html
    logo: archive/clock-history.png
  search: true

bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    fontsize: 1.2em
    highlight-style: breezedark # monokai # breezedark # espresso
    include-in-header:
      - includes.html
  pdf:
    documentclass: scrreprt



