project:
  type: book
  output-dir: docs


book:
  title: "Time Series Analysis"
  author: "Yair Mau"
  repo-url: https://github.com/yairmau/time-series/
  favicon: archive/clock-history.png
  chapters:
    - index.qmd
    - who-cares.qmd
    - part: "start here"
      chapters:
      - basics/boring.qmd
      - basics/numpy-pandas-matplotlib.qmd
      - basics/example.ipynb
      - basics/AI-policy.qmd
    - part: "resampling"
      chapters:
        - resampling/motivation.ipynb
        - resampling/resampling.ipynb
        - resampling/upsampling.ipynb
        - resampling/interpolation.ipynb
        - resampling/FAQ.ipynb
    - part: "smoothing"
      chapters:
        - smoothing/motivation.ipynb
        - smoothing/sliding.ipynb
        - smoothing/not-only-averages.ipynb
        - smoothing/fit.ipynb
        - smoothing/savgol.ipynb
        # - smoothing/LOESS.qmd
        # - smoothing/perfect-smoother.qmd
    - part: "outliers and gaps"
      chapters:
      - outliers/motivation.qmd
      - outliers/outlier-identification.ipynb
      - outliers/robust-analysis.ipynb
      - outliers/sliding-algorithms.ipynb
      - outliers/substituting-outliers.ipynb
      # - outliers/interpolation.ipynb
      - outliers/outliers_challenge.ipynb
      - outliers/outliers_challenge_part2.ipynb
    
    - part: "stationarity"
      chapters:
        - stationarity/motivation.qmd
        - stationarity/random.qmd
        - stationarity/AR.qmd
        - stationarity/autocorrelation.qmd
        - stationarity/stationarity.qmd
        - stationarity/ACF_and_PACF_graphs.ipynb
        - stationarity/from_AR_to_ARIMA.ipynb
        - stationarity/practice.ipynb
        - stationarity/practice2.ipynb
    - part: "seasonality"
      chapters:
        - seasonality/motivation.qmd
        - seasonality/seasonal-decomposition-from-scratch.ipynb
        - seasonality/theory.ipynb
        - seasonality/widget.ipynb
        # - seasonality/seasonal-decomposition.ipynb
        # - seasonality/hilbert.qmd
    - part: "time lags"
      chapters:
        - lags/motivation.qmd
        - lags/cross-correlation.ipynb
        - lags/DTW.ipynb
        - lags/lags_TA.ipynb
    - part: "frequency"
      chapters:
        - frequency/motivation.qmd
        - frequency/fourier.ipynb
        - frequency/dft-and-fft.ipynb
        - frequency/sound.ipynb
        - frequency/frequencies.ipynb
        - frequency/filtering.ipynb
        - frequency/fft_practice_temperature.ipynb
        - frequency/fft_practice_stomata.ipynb
        - frequency/fft_practice_stayin_alive.ipynb
        - frequency/filtering_temp.ipynb
        - frequency/filtering_scipy.ipynb
        - frequency/filtering_hummus.ipynb
        
    - part: "rates of change"
      chapters:
        - rates-of-change/motivation.ipynb
        - rates-of-change/finite-differences.ipynb
        - rates-of-change/fourier-based-derivatives.ipynb
        - rates-of-change/LOESS-based-derivatives.ipynb
        - rates-of-change/does-order-matter.ipynb
    - part: "forecasting"
      chapters:
        - forecasting/motivation.qmd
        - forecasting/arima.qmd
    - part: "assignments"
      chapters:
        - assignments/assignment1.qmd
        - assignments/assignment2.ipynb
        - assignments/assignment3.ipynb
        - assignments/final-project.qmd
    - part: "technical stuff"
      chapters:
        - technical-stuff/technical-stuff.qmd
        - technical-stuff/datasets.qmd
        - technical-stuff/date-formatting.ipynb
        - technical-stuff/sources.qmd
    - part: "behind-the-scenes"
      chapters:
      - behind-the-scenes/sliding-window-video.ipynb
      - behind-the-scenes/savgol-video.ipynb
      - behind-the-scenes/API-IMS.ipynb
      - behind-the-scenes/consecutive_sequence.ipynb
      - behind-the-scenes/outliers_graphs.ipynb
      - behind-the-scenes/make_your_own_website.qmd
  sidebar:
    collapse-level: 2
    tools:
      - icon: house-fill
        href: https://yairmau.com/
      - icon: bookmark-fill
        href: /sources.html
      - icon: asterisk
        href: /things-to-remember.html
    logo: archive/clock-history.png
  search: true

bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    # - font_defs.css
    # css: styles.css
    fontsize: 1.2em
    highlight-style: breezedark # monokai # breezedark # espresso
    include-in-header:
      - includes.html
      # progress bar and back to top button. solution from here: https://github.com/quarto-dev/quarto-cli/discussions/3842#discussioncomment-4591721
      # - back-to-top.html
      - progressbar.html
    code-line-numbers: true
    code-tools:
      source: repo  # https://quarto.org/docs/output-formats/html-code.html#code-tools
    callout-icon: false
    fig-align: center
    # the default MathJax rendering option yields ugly results, use katex
    html-math-method: katex
  
  pdf:
    documentclass: scrreprt
    include-in-header:
      - latex_preamble.tex




