project:
  type: book
  output-dir: docs


book:
  title: "Time Series Analysis"
  author: "Yair Mau"
  # date: "12/24/2022"
  chapters:
    - index.qmd
    - first-steps/first-steps.ipynb
    - convolution/index.qmd
    - seasonal-decomposition/seasonal-decomposition.ipynb
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    fontsize: 1.2em
    highlight-style: gruvbox
  pdf:
    documentclass: scrreprt



