project:
  type: book
  output-dir: docs


book:
  title: "Time Series Analysis"
  author: "Yair Mau"
  repo-url: https://github.com/yairmau/time-series/
  favicon: archive/clock-history.png
  chapters:
    - index.qmd
    - who-cares.qmd
    - part: "start here"
      chapters:
      - basics/boring.qmd
      - basics/numpy-pandas-matplotlib.qmd
      - basics/example.ipynb
      - basics/AI-policy.qmd
    - part: "resampling"
      chapters:
        - resampling/motivation.ipynb
        - resampling/resampling.ipynb
        - resampling/upsampling.ipynb
        - resampling/interpolation.ipynb
        - resampling/FAQ.ipynb
    - part: "smoothing"
      chapters:
        - smoothing/motivation.ipynb
        - smoothing/sliding.ipynb
        - smoothing/not-only-averages.ipynb
        - smoothing/fit.ipynb
        - smoothing/savgol.ipynb
        # - smoothing/LOESS.qmd
        # - smoothing/perfect-smoother.qmd
    - part: "outliers and gaps"
      chapters:
      - outliers/motivation.qmd
      - outliers/outlier-identification.ipynb
      - outliers/robust-analysis.ipynb
      - outliers/sliding-algorithms.ipynb
      - outliers/substituting-outliers.ipynb
      - outliers/interpolation.ipynb
    - part: "best practices"
      chapters:
        - best-practices/motivation.qmd
        - best-practices/date-formatting.ipynb
    - part: "stationarity"
      chapters:
        - stationarity/motivation.qmd
        - stationarity/stochastic.qmd
        - stationarity/autocorrelation.qmd
    - part: "time lags"
      chapters:
        - lags/motivation.qmd
        - lags/cross-correlation.ipynb
        - lags/dynamic-time-warp.qmd
        - lags/LDTW.ipynb
    - part: "frequency"
      chapters:
        - frequency/motivation.qmd
        - frequency/fourier.qmd
        - frequency/filtering.qmd
        - frequency/nyquist.qmd
    - part: "seasonality"
      chapters:
        - seasonality/motivation.qmd
        - seasonality/seasonal-decomposition.ipynb
        - seasonality/hilbert.qmd
    - part: "rates of change"
      chapters:
        - rates-of-change/motivation.ipynb
        - rates-of-change/derivatives.qmd
        - rates-of-change/finite-differences.qmd
        - rates-of-change/fourier-based-derivatives.qmd
        - rates-of-change/LOESS-based-derivatives.qmd
    - part: "forecasting"
      chapters:
        - forecasting/motivation.qmd
        - forecasting/arima.qmd
    - part: "assignments"
      chapters:
        - assignments/assignment1.qmd
        - assignments/assignment2.ipynb
        # - assignments/assignment_final.qmd
    - part: "technical stuff"
      chapters:
        - technical-stuff/technical-stuff.qmd
        - technical-stuff/datasets.qmd
    - part: "behind-the-scenes"
      chapters:
      - behind-the-scenes/sliding-window-video.ipynb
      - behind-the-scenes/savgol-video.ipynb
      - behind-the-scenes/API-IMS.ipynb
      - behind-the-scenes/consecutive_sequence.ipynb
  sidebar:
    collapse-level: 2
    tools:
      - icon: house-fill
        href: https://yairmau.com/
      - icon: bookmark-fill
        href: /references.html
      - icon: asterisk
        href: /things-to-remember.html
    logo: archive/clock-history.png
  search: true

bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    # - font_defs.css
    # css: styles.css
    fontsize: 1.2em
    highlight-style: breezedark # monokai # breezedark # espresso
    include-in-header:
      - includes.html
    code-line-numbers: true
    code-tools:
      source: repo  # https://quarto.org/docs/output-formats/html-code.html#code-tools
    callout-icon: false
    fig-align: center
    # the default MathJax rendering option yields ugly results, use katex
    html-math-method: katex
  
  pdf:
    documentclass: scrreprt
    include-in-header:
      - latex_preamble.tex




