project:
  type: book
  output-dir: docs


book:
  title: "Time Series Analysis"
  author: "Yair Mau"
  repo-url: https://github.com/yairmau/time-series/
  favicon: archive/clock-history.png
  chapters:
    - index.qmd
    - who-cares.qmd
    - part: "start here"
      chapters:
      - basics/boring.qmd
      - basics/pandas.qmd
      - basics/pyplot.qmd
      - basics/example.ipynb
    - part: "resampling"
      chapters:
        - resampling/motivation.ipynb
        - resampling/resampling.ipynb
        - resampling/upsampling.qmd
    - part: "outliers and gaps"
      chapters:
      - outliers/motivation.qmd
      - outliers/zscore.qmd
      - outliers/IQR.qmd

    - part: "best practices"
      chapters:
        - best-practices/motivation.qmd
        - best-practices/dates.qmd
    - part: "smoothing"
      chapters:
        - smoothing/motivation.qmd
        - smoothing/convolution.qmd
        - smoothing/LOESS.qmd
        - smoothing/perfect-smoother.qmd
    - part: "stationarity"
      chapters:
        - stationarity/motivation.qmd
        - stationarity/stochastic.qmd
        - stationarity/autocorrelation.qmd
    - part: "time lags"
      chapters:
        - lags/motivation.qmd
        - lags/cross-correlation.ipynb
        - lags/dynamic-time-warp.qmd
        - lags/LDTW.ipynb
    - part: "frequency"
      chapters:
        - frequency/motivation.qmd
        - frequency/fourier.qmd
        - frequency/filtering.qmd
        - frequency/nyquist.qmd
    - part: "seasonality"
      chapters:
        - seasonality/motivation.qmd
        - seasonality/seasonal-decomposition.ipynb
        - seasonality/hilbert.qmd
    - part: "rates of change"
      chapters:
        - rates-of-change/motivation.qmd
        - rates-of-change/derivatives.qmd
        - rates-of-change/finite-differences.qmd
        - rates-of-change/fourier-based-derivatives.qmd
        - rates-of-change/LOESS-based-derivatives.qmd
    - part: "forecasting"
      chapters:
        - forecasting/motivation.qmd
        - forecasting/arima.qmd
    - technical-stuff/technical-stuff.qmd
    - references.qmd
  sidebar:
    collapse-level: 2
    tools:
      - icon: house-fill
        href: https://yairmau.com/
      - icon: bookmark-fill
        href: /references.html
    logo: archive/clock-history.png
  search: true

bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    # - font_defs.css
    # css: styles.css
    fontsize: 1.2em
    highlight-style: breezedark # monokai # breezedark # espresso
    include-in-header:
      - includes.html
    code-line-numbers: true
    code-tools:
      source: repo  # https://quarto.org/docs/output-formats/html-code.html#code-tools
  
  pdf:
    documentclass: scrreprt
    include-in-header:
      - latex_preamble.tex




