## who cares? {.unnumbered}

## why "Time Series Analysis?"

<div class="alert alert-info">
Time has two aspects. There is the arrow, the running river, without which there is no change, no progress, or direction, or creation. And there is the circle or the cycle, without which there is chaos, meaningless succession of instants, a world without clocks or seasons or promises.  
  URSULA K. LE GUIN</div>

You are here because you are interested in how things change, evolve. In this course I want to discuss with you how to make sense of data whose temporal nature is in its very essence. We will talk about randomness, cycles, frequencies, correlations, and more.


## why "Environmental Sciences"

This same time series analysis (TSA) course could be called instead "TSA for finance", "TSA for Biology", or any other application. The emphasis in this course is **not** Environmental Sciences, but the concepts and tools of TSA. Because my research is in Environmental Science, and many of the graduate students at HUJI-Rehovot research this, I chose to use examples "close to home". The same toolset should be useful for students of other disciplines.

## what is it good for?

In many fields of science we are flooded by data, and it's hard to see the forest for the trees. I hope that the topics we'll discuss in this course can help you find meaningful patterns in your data, formulate interesting hypotheses, and design better experiments.


## do I need it?

Maybe. If you are a grad student and you have temporal data to analyze, then probably yes. However, I have very fond memories of courses that I took as a grad student that were completely unrelated to my research. Sometimes "because it's fun" is a perfectly good answer.

## what will I **actually** gain from it?

By the end of this course you will have gained:

* a **hands-on** experience of fundamental time-series analysis tools
* an **intuition** regarding the basic concepts
* **technical** abilities
* a **springboard** for learning more about the subject by yourself